name = "minichat-backend"
type = "webpack"
workers_dev = true
route = "minichat-backend.worker.dev" # Cambia esto a tu dominio personalizado si lo tienes



[build]
  command = "npm start"
  upload_format = "service-worker"
  watch = false  # Esto detiene la construcción después de iniciar tu servidor
  pages_build_output_dir = "./src"
  